project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2425/*"
    - "!00activetest.qmd"
  output-dir: ../docs/2526/labs2011211-2015-101519918-61518-1-16189265/

website:
  title: "USMR"
  navbar:
    background: primary
    search: true
    left: 
      - text: "Intro to R & Statistics"
        menu: 
          - 01_ex.qmd
          - 02_ex.qmd
          - 03_ex.qmd
          - 04_ex.qmd
      - text: "Linear Models"
        menu: 
          - 05_ex.qmd
          - 07_ex.qmd
          - 08_ex.qmd
          - 09_ex.qmd
          - 10_ex.qmd
          - 11_ex.qmd
format:
  live-html:
    toc: true
    toc_float: true
    code-annotations: hover
    link-citations: true
    theme: 
      - united
      - assets/style-labs.scss
      - assets/active/_style.scss
      - assets/active/_webex.scss
    include-after-body: 
      - assets/active/_webex.js
      - assets/active/_displayall.js
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    number-sections: false
webr: 
  packages: ['learnr']


